### PR TITLE
InlineQueryResultArticle and Mouse Over Text

### PR DESCRIPTION
**Pull request by j-maas**
I really liked your bot and wanted to modify it slightly:

- Instead of an InlineQueryResultPhoto I wanted it to return InlineQueryResultArticles and use the link preview to show the image.
- I wanted to have the mouse over text accessible from inside Telegram.

I implemented these features and took the opportunity to port your code to TypeScript and use the Telegraf framework instead of Telebot. Typings are currently being added to Telegraf and this unfortunately means that the code is currently slightly messy...

I opened this PR mainly because I wanted to ask you, if you like these changes and want to merge these into your repo. I do not want to take your bot away. ;)  
However, if you do not like the changes I've made, I could just host a separate bot myself.

### CODE REVIEW

**Comment by wojpawlik** [comment]
Hello :)

Sorry for the delay, I haven't received any notification.

This is the first time ever someone made a pull request to my project :) So I was amazed when I noticed.

You have some interesting ideas, like [`console.log('Outgoing:\n', await next())`](https://github.com/Y0hy0h/xkcd-search-bot/blob/aaa1e3dfb29d1fa5004271be776ebcdf616e26bc/src/startBot.ts#L31).

And, if I wrote the bot now, I would've used Telegraf (or micro-bot, to be exact) as well.

Still, there are some architectural changes I disagree with. I won't merge it.

> I could just host a separate bot myself.

Yeah, do that. And when you do, please tell me what its username is, I'd love to check it out (and maybe steal some ideas ;) )

**Comment by wojpawlik** [comment]
Also, small hint, you may want to enable Issues in your fork; it's disabled by default in forks, but when your fork diverges, you could benefit from them.

**Comment by j-maas** [comment]
Do you mind explaining to me what changes you don't like? Even if we disagree, it would be interesting for me to hear your position on this. :)

Also thanks for the hint about issues in forks. I didn't know that and will enable them.

**Comment by j-maas** [comment]
I was just trying to get the bot up and [running on Glitch](https://glitch.com/~xkcd-for-that-bot) when you responded. :D The username is [`@xkcdForThatBot`](https://t.me/xkcdForThatBot)

**Comment by wojpawlik** [comment]
Used your bot, I admit, I like its UX :)

> Do you mind explaining to me what changes you don't like? Even if we disagree, it would be interesting for me to hear your position on this. :)

- `process.env.ENVIRONMENT='DEBUG'` -- `process.env.NODE_ENV='development'` is a known practice in Node community.

- TypeScript -- I'm starting to enjoy benefits of type-checked JS (and experiencing the pain when there is a lacking definition, or code fails typechecking for mysterious reason), I'd consider using TypeScript on front-end, where you pretty much have to transpile if you want to do anything serious, and don't want to worry about browser support every second, but as Node has pretty good JS support, I wouldn't complicate my (simple) Node projects with transpiling. I annotate my JS with JSDoc and typecheck that.

  But, that's just me. Not saying it's wrong. Just, I wouldn't do that at this point.

- General complexity -- some code feels overengineered. Especially [`src/bot/telegram`](https://github.com/Y0hy0h/xkcd-for-that-bot/blob/4c919304ac70b8936ca2206609da87393ed7acc2/src/bot/telegram.ts)... do you really need it?

  Maybe there are other things which I'd call overengineering, I haven't studied the whole codebase that carefully, that one file just caught my attention.

Also, I wouldn't mind if you didn't mention that it's a fork of my bot, at this point you pretty much rewrote everything. Not saying that I don't want you to mention, just don't feel like you have to.

**Comment by j-maas** [comment]
- Thanks for the feedback! I think I will change the environment flag to fit the convention, wasn't aware of that.

- I find type systems really helpful, since I've run into bugs too often when feeding the wrong input into a badly documented function. :)

-  I agree, some parts are a bit overcomplicated. The `telegram.ts` is just a placeholder because I'm not happy with the current typings for Telegraf (they're in development). I found them pretty confusing, that's why I opted to just put in my own.  
   That said, I agree that the code is not perfectly architectured. Maybe in the future I'll be able to fix that.

I'd like to keep the reference to your bot. It's just fair, in my opinion, and your bot was very good starting point for this project. :)  
(You wrote you didn't mind, but just in case: If you'd like me to remove the reference, even if it's just that you feel slightly uncomfortable or whatever, just tell me. :D )

**Pull request closed without merging**
